<!-- 日本地図 -->
<div id="my-map"></div>
<script>
    var areaLinks = {
        1:"./products.php?prefId=1",
        2:"./products.php?prefId=2",
        3:"./products.php?prefId=3",
        4:"./products.php?prefId=4",
        5:"./products.php?prefId=5",
        6:"./products.php?prefId=6",
        7:"./products.php?prefId=7",
        8:"./products.php?prefId=8",
        9:"./products.php?prefId=9",
        10:"./products.php?prefId=10",
        11:"./products.php?prefId=11",
        12:"./products.php?prefId=12",
        13:"./products.php?prefId=13",
        14:"./products.php?prefId=14",
        15:"./products.php?prefId=15",
        16:"./products.php?prefId=16",
        17:"./products.php?prefId=17",
        18:"./products.php?prefId=18",
        19:"./products.php?prefId=19",
        20:"./products.php?prefId=20",
        21:"./products.php?prefId=21",
        22:"./products.php?prefId=22",
        23:"./products.php?prefId=23",
        24:"./products.php?prefId=24",
        25:"./products.php?prefId=25",
        26:"./products.php?prefId=26",
        27:"./products.php?prefId=27",
        28:"./products.php?prefId=28",
        29:"./products.php?prefId=29",
        30:"./products.php?prefId=30",
        31:"./products.php?prefId=31",
        32:"./products.php?prefId=32",
        33:"./products.php?prefId=33",
        34:"./products.php?prefId=34",
        35:"./products.php?prefId=35",
        36:"./products.php?prefId=36",
        37:"./products.php?prefId=37",
        38:"./products.php?prefId=38",
        39:"./products.php?prefId=39",
        40:"./products.php?prefId=40",
        41:"./products.php?prefId=41",
        42:"./products.php?prefId=42",
        43:"./products.php?prefId=43",
        44:"./products.php?prefId=44",
        45:"./products.php?prefId=45",
        46:"./products.php?prefId=46",
        47:"./products.php?prefId=47",
    };

    var d = new jpmap.japanMap(document.getElementById("my-map"), {
        areas: [
        {code : 1, name: "北海道", color: "#7f7eda", hoverColor: "#b3b2ee"},
        {code : 2, name: "青森", color: "#759ef4", hoverColor: "#98b9ff"},
        {code : 3, name: "岩手", color: "#759ef4", hoverColor: "#98b9ff"},
        {code : 4, name: "宮城", color: "#759ef4", hoverColor: "#98b9ff"},
        {code : 5, name: "秋田", color: "#759ef4", hoverColor: "#98b9ff"},
        {code : 6, name: "山形", color: "#759ef4", hoverColor: "#98b9ff"},
        {code : 7, name: "福島", color: "#759ef4", hoverColor: "#98b9ff"},
        {code : 8, name: "茨城", color: "#7ecfea", hoverColor: "#b7e5f4"},
        {code : 9, name: "栃木", color: "#7ecfea", hoverColor: "#b7e5f4"},
        {code : 10, name: "群馬", color: "#7ecfea", hoverColor: "#b7e5f4"},
        {code : 11, name: "埼玉", color: "#7ecfea", hoverColor: "#b7e5f4"},
        {code : 12, name: "千葉", color: "#7ecfea", hoverColor: "#b7e5f4"},
        {code : 13, name: "東京", color: "#7ecfea", hoverColor: "#b7e5f4"},
        {code : 14, name: "神奈川", color: "#7ecfea", hoverColor: "#b7e5f4"},
        {code : 15, name: "新潟", color: "#7cdc92", hoverColor: "#aceebb"},
        {code : 16, name: "富山", color: "#7cdc92", hoverColor: "#aceebb"},
        {code : 17, name: "石川", color: "#7cdc92", hoverColor: "#aceebb"},
        {code : 18, name: "福井", color: "#7cdc92", hoverColor: "#aceebb"},
        {code : 19, name: "山梨", color: "#7cdc92", hoverColor: "#aceebb"},
        {code : 20, name: "長野", color: "#7cdc92", hoverColor: "#aceebb"},
        {code : 21, name: "岐阜", color: "#7cdc92", hoverColor: "#aceebb"},
        {code : 22, name: "静岡", color: "#7cdc92", hoverColor: "#aceebb"},
        {code : 23, name: "愛知", color: "#7cdc92", hoverColor: "#aceebb"},
        {code : 24, name: "三重", color: "#ffe966", hoverColor: "#fff19c"},
        {code : 25, name: "滋賀", color: "#ffe966", hoverColor: "#fff19c"},
        {code : 26, name: "京都", color: "#ffe966", hoverColor: "#fff19c"},
        {code : 27, name: "大阪", color: "#ffe966", hoverColor: "#fff19c"},
        {code : 28, name: "兵庫", color: "#ffe966", hoverColor: "#fff19c"},
        {code : 29, name: "奈良", color: "#ffe966", hoverColor: "#fff19c"},
        {code : 30, name: "和歌山", color: "#ffe966", hoverColor: "#fff19c"},
        {code : 31, name: "鳥取", color: "#ffcc66", hoverColor: "#ffe0a3"},
        {code : 32, name: "島根", color: "#ffcc66", hoverColor: "#ffe0a3"},
        {code : 33, name: "岡山", color: "#ffcc66", hoverColor: "#ffe0a3"},
        {code : 34, name: "広島", color: "#ffcc66", hoverColor: "#ffe0a3"},
        {code : 35, name: "山口", color: "#ffcc66", hoverColor: "#ffe0a3"},
        {code : 36, name: "徳島", color: "#fb9466", hoverColor: "#ffbb9c"},
        {code : 37, name: "香川", color: "#fb9466", hoverColor: "#ffbb9c"},
        {code : 38, name: "愛媛", color: "#fb9466", hoverColor: "#ffbb9c"},
        {code : 39, name: "高知", color: "#fb9466", hoverColor: "#ffbb9c"},
        {code : 40, name: "福岡", color: "#ff9999", hoverColor: "#ffbdbd"},
        {code : 41, name: "佐賀", color: "#ff9999", hoverColor: "#ffbdbd"},
        {code : 42, name: "長崎", color: "#ff9999", hoverColor: "#ffbdbd"},
        {code : 43, name: "熊本", color: "#ff9999", hoverColor: "#ffbdbd"},
        {code : 44, name: "大分", color: "#ff9999", hoverColor: "#ffbdbd"},
        {code : 45, name: "宮崎", color: "#ff9999", hoverColor: "#ffbdbd"},
        {code : 46, name: "鹿児島", color: "#ff9999", hoverColor: "#ffbdbd"},
        {code : 47, name: "沖縄", color: "#eb98ff", hoverColor: "#f5c9ff"},
        ],

        // 都道府県名表示
        // showsprefIdectureName: true,
        // 地図のサイズ指定
        width: 800,
        // 地図の背景色
        backgroundColor: "#f8f8f8",
        // 沖縄県を左上に表示
        movesIslands: true,
        // 表示されている都道府県名を日本語で表示
        lang: "ja",
        onSelect: function(data) {
            location.href = areaLinks[data.area.code];
        }
        // onHover: function(data) {
        //     alert(data.name);
        // }
    });
</script>